### ISSUE TITLE
Request: Add a License File

### ISSUE THREAD

**Issue by dginovker** [KripC2160/findmealinuxdistro#11]
The website is 10/10 and fantastic, but I had an idea of remastering it to work for finding amazing, niche and top tier Linux apps. However without a license file, I can't fork and host it.

Github offers fantastic support for adding licenses, you can just do the following:

Add File > Create new File
![image](https://user-images.githubusercontent.com/32943174/115999973-48475080-a5bc-11eb-81f4-ddd2ccfa1f94.png)

Type in LICENSE and "Choose license template" will pop up
![image](https://user-images.githubusercontent.com/32943174/115999989-5ac18a00-a5bc-11eb-92aa-8efbd7a4e9b5.png)

I recommend GPL v3, the same as the Linux kernel, which (in practice) means anybody who uses your code also has to share the code as well, but other licenses work too.

**Comment by KripC2160** [comment]
안녕하세요! 저작권을 만들었으니까 마음껏 쓰세요. (GPL v3)
