### ISSUE TITLE
Suicide Linux

### ISSUE THREAD

**Issue by qx-775** [KripC2160/findmealinuxdistro#8]
Hello,

petition to add Suicide Linux to the list:
https://github.com/tiagoad/suicide-linux

more from the author:

> I have invented Suicide Linux. Any time - any time - you type any remotely incorrect command, the interpreter creatively resolves it into rm -rf / and wipes your hard drive.

Thank you.

**Comment by KripC2160** [comment]
When I first saw the title I was a little concerned but after looking at it it's an interesting distro lol I will add it :)

**Comment by qx-775** [comment]
I love you

**Comment by KripC2160** [comment]
No problem ;)
